### ISSUE TITLE
Go 1.6 で使えない

### ISSUE THREAD

**Issue by s-yata** [groonga/grngo#28]
#### 概要

Go 1.6 では使えませんでした．

**Comment by s-yata** [comment]
Go 1.6 において `go test` が失敗することは確認しました．

```
$ go test
--- FAIL: TestColumn (0.08s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
    panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 24 [running]:
panic(0x5910c0, 0xc820414ee0)
    /home/s-yata/go/root/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8200a0360)
    /home/s-yata/go/root/src/testing/testing.go:467 +0x192
panic(0x5910c0, 0xc820414ee0)
    /home/s-yata/go/root/src/runtime/panic.go:426 +0x4e9
_/home/s-yata/git/groonga/grngo.(*Column).SetValue(0xc820416520, 0x1, 0x54bee0, 0xc820416740, 0x0, 0x0)
    /home/s-yata/git/groonga/grngo/grngo.go:1206 +0x15fd
_/home/s-yata/git/groonga/grngo.testColumn(0xc8200a0360, 0xc82039abd0, 0x5c9070, 0xb, 0xc820041ab0, 0x64, 0x64, 0xc8203a3701)
    /home/s-yata/git/groonga/grngo/grngo_test.go:504 +0x468
_/home/s-yata/git/groonga/grngo.TestColumn(0xc8200a0360)
    /home/s-yata/git/groonga/grngo/grngo_test.go:545 +0x48d
testing.tRunner(0xc8200a0360, 0x89cfb8)
    /home/s-yata/go/root/src/testing/testing.go:473 +0x98
created by testing.RunTests
    /home/s-yata/go/root/src/testing/testing.go:582 +0x892
exit status 2
FAIL    _/home/s-yata/git/groonga/grngo 1.610s
```

**Comment by s-yata** [comment]
`SetValue()` は使えません．
とりあえず `SetValue()` を使っていて失敗するテストは無効にしておきました．

**Comment by s-yata** [comment]
`SetValue()` を頑張るのはあまり筋がよろしくなさそうなので，諦めることにします．
